name: dio_http_cache
description: http cache lib for Flutter dio like RxCache.It use sqflite as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.3.0
authors:
  - Hurshi <ihsruh@gmail.com>
  - Eric Kok <erickok@gmail.com>
  - Amit <ithebest27@gmail.com>
homepage: https://github.com/hurshi/dio-http-cache

environment:
  sdk: '>=2.12.0 <5.0.0'

dependencies:
  crypto: ^3.0.6
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  path: ^1.9.1
  quiver: ^3.2.2
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true
